//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deceased
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deceased()
        {
            this.Order_Grave = new HashSet<Order_Grave>();
        }
    
        public int id { get; set; }
        public Nullable<int> deceased_status_id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string patronymic { get; set; }
        public System.DateTime birth_date { get; set; }
        public System.DateTime death_date { get; set; }
        public Nullable<int> deleted { get; set; }
    
        public virtual DeceasedStatus DeceasedStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Grave> Order_Grave { get; set; }
    }
}
