//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARU
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ARUDBEntities : DbContext
    {
        public ARUDBEntities()
            : base("name=ARUDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Deceased> Deceased { get; set; }
        public virtual DbSet<DeceasedStatus> DeceasedStatus { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Grave> Grave { get; set; }
        public virtual DbSet<GraveStatus> GraveStatus { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Order_Grave> Order_Grave { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Status> Status { get; set; }
    }
}
